In [1]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

c:\Users\uif29726\AppData\Local\anaconda3\envs\tokens\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# Step 1: Initialize the Tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Step 2: Tokenize the Sentences
sentences = ["The train is coming down the railroad.", "I would like to train for the marathon."]
inputs = tokenizer(sentences, return_tensors="tf", padding=True, truncation=True)
print("Tokenized inputs:", inputs)


Tokenized inputs: {'input_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[ 101, 1996, 3345, 2003, 2746, 2091, 1996, 4296, 1012,  102,    0],
       [ 101, 1045, 2052, 2066, 2000, 3345, 2005, 1996, 8589, 1012,  102]])>, 'token_type_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Model: "tf_bert_model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109,482,240
Trainable params: 109,482,240
Non-trainable params: 0
_________________________________________________________________
Output type: <class 'transformers.modeling_tf_outputs.TFBaseModelOutputWithPoolingAndCrossAttentions'>
Last hidden state shape: (2, 11, 768)
Embeddings: tf.Tensor(
[[[ 0.10757083  0.3880875   0.12968853 ... -0.4632478   0.1166324
    0.23986953]
  [-0.20239697 -0.42824233 -0.7406918  ... -0.20015913  0.6608236
   -0.06402533]
  [ 1.1334908  -0.44801068  0.25663394 ... -0.5473359   0.42921066
   -0.2071341 ]
  ...
  [ 0.5309195   0.43836066 -0.15911084 ... -0.23734377  0.05778742
   -0.58127695]
  [-0.22118981  0.07114679  0.07976199 ... -0.14295687  0.0792342

In [ ]:
# Step 3: Load the BERT Model from a local path
local_model_path = 'models/bert-base-uncased'
bert_model = TFBertModel.from_pretrained(local_model_path)
bert_model.summary()

In [ ]:
# Step 4: Get the Embeddings
outputs = bert_model(inputs)
print("Output type:", type(outputs))
print("Last hidden state shape:", outputs.last_hidden_state.shape)

# Step 5: Extract the Embeddings
embeddings = outputs.last_hidden_state
print("Embeddings:", embeddings)

In [9]:
local_model_path = 'models\\bert-base-uncased'

# Step 3: Load the BERT Model from a local path
bert_model = TFBertModel.from_pretrained(local_model_path)
bert_model.summary()

# Step 4: Get the Embeddings
outputs = bert_model(inputs)
print("Output type:", type(outputs))
print("Last hidden state shape:", outputs.last_hidden_state.shape)

# Step 5: Extract the Embeddings
embeddings = outputs.last_hidden_state
print("Embeddings:", embeddings)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Model: "tf_bert_model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109,482,240
Trainable params: 109,482,240
Non-trainable params: 0
_________________________________________________________________
Output type: <class 'transformers.modeling_tf_outputs.TFBaseModelOutputWithPoolingAndCrossAttentions'>
Last hidden state shape: (1, 10, 768)
Embeddings: tf.Tensor(
[[[ 0.11519857  0.4218652  -0.07239948 ... -0.31876746  0.42083034
    0.3457224 ]
  [ 0.5871951   0.47900453 -0.26907337 ... -0.47323546  1.5698124
   -0.5054238 ]
  [ 0.7203411   0.24260135  0.17398909 ... -0.5581568   0.66156596
    0.31098303]
  ...
  [ 0.18190551  0.45673084  0.4914439  ...  0.50699973  0.08128806
    0.31542805]
  [ 0.6777957   0.03997956 -0.35449222 ...  0.19579566 -0.469921

In [19]:
# Step 6: Identify the position of the token 'train' in both sentences
tokens_1 = tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])
tokens_2 = tokenizer.convert_ids_to_tokens(inputs['input_ids'][1])
print("Tokens 1:", tokens_1)
print("Tokens 2:", tokens_2)

# Find the index of the token 'train' in both tokenized sentences
index_train_1 = tokens_1.index('train')
index_train_2 = tokens_2.index('train')

size_train_1 = len(tokens_1)
size_train_2 = len(tokens_2)

print("Index of 'train' in sentence 1:", index_train_1)
print("Index of 'train' in sentence 2:", index_train_2)

# Extract the embeddings for the token 'train' in both sentences
embedding_train_1 = embeddings[0, index_train_1, :]
embedding_train_2 = embeddings[1, index_train_2, :]

size_train_1 = len(embedding_train_1)
size_train_2 = len(embedding_train_2)

print("Size of embedding for 'train' in sentence 1:", size_train_1)
print("Size of embedding for 'train' in sentence 2:", size_train_2)

print("Embedding for 'train' in sentence 1:", embedding_train_1[:10])
print("Embedding for 'train' in sentence 2:", embedding_train_2[:10])

Tokens 1: ['[CLS]', 'the', 'train', 'is', 'coming', 'down', 'the', 'railroad', '.', '[SEP]', '[PAD]']
Tokens 2: ['[CLS]', 'i', 'would', 'like', 'to', 'train', 'for', 'the', 'marathon', '.', '[SEP]']
Index of 'train' in sentence 1: 2
Index of 'train' in sentence 2: 5
Size of embedding for 'train' in sentence 1: 768
Size of embedding for 'train' in sentence 2: 768
Embedding for 'train' in sentence 1: tf.Tensor(
[ 1.1334908  -0.44801068  0.25663394  0.05864524  0.08220526 -0.43779406
  0.94841     1.1336415   0.36283237 -0.24162242], shape=(10,), dtype=float32)
Embedding for 'train' in sentence 2: tf.Tensor(
[ 1.2525578  -0.01590084  0.22371037 -0.39468217 -0.633641   -0.5781268
  0.15272336  0.4784645   0.66080505  0.41733947], shape=(10,), dtype=float32)


In [18]:
# Compare the embeddings
similarity = tf.keras.losses.cosine_similarity(embedding_train_1, embedding_train_2)
print("Cosine similarity between the embeddings:", similarity.numpy())

Cosine similarity between the embeddings: -0.44399095
